apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  labels:
    app: my-app-svc

spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: my-port
      port: 80
      targetPort: 80
      nodePort: 30000
